---
# tasks file for db

- name: Install Mysql package
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
   - "{{ mysql_packs }}"

# - name: Create Mysql configuration file
#   template:
     # src: my.cnf.j2
     # dest: /etc/my.cnf
#   notify:
#   - restart mysql

- name: open mysqld port
  firewalld:
    port: "{{ mysqld_port }}/tcp"
    zone: public
    permanent: true
    immediate: true
    state: enabled

- name: start and enable mysql service
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: Create Application DB User
  mysql_user:
    name: "{{ mysql_username }}"
    password: "{{ mysql_password }}"
    priv: '*.*:ALL'
    host: '%'
    state: present

- name: Configure SELinux to start mysql on any port
  seboolean:
    name: mysql_connect_any
    state: true
    persistent: yes
