---
# tasks file for db

- name: install the MySQL repo.
  yum:
    name: "{{ mysql_repo }}"
    state: present

- name: install Mysql packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
   - "{{ mysql_packs }}"

# - name: Create Mysql configuration file
#   template:
     # src: my.cnf.j2
     # dest: /etc/my.cnf
#   notify:
#   - restart mysql

- name: check if firewalld is running
  service:
    name: firewalld
    state: started
  check_mode: yes
  register: firewalld_service_status

- name: open mysqld port
  firewalld:
    port: "{{ mysqld_port }}/tcp"
    zone: public
    permanent: true
    immediate: true
    state: enabled
  when: firewalld_service_status.changed == false

- name: start and enable mysql service
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: get temporary password
  shell: |
    awk '/A temporary password is generated for/' /var/log/mysqld.log |
    awk '{print $(NF)}'
  register: mysql_temp_pass

- name: change temporary root password
  mysql_user:
    login_password: "{{ mysql_temp_pass }}"
    name: root
    password: "{{ mysql_root_password }}"

- name: create DB user
  mysql_user:
    login_name: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_username }}"
    password: "{{ mysql_password }}"
    priv: '*.*:ALL'
    host: '%'
    state: present

- name: configure SELinux to start mysql on any port
  seboolean:
    name: mysql_connect_any
    state: true
    persistent: yes

