---
# tasks file for db

- name: install the MySQL repo.
  yum:
    name: "{{ mysql_repo }}"
    state: present

- name: install Mysql packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
   - "{{ mysql_packs }}"

# - name: Create Mysql configuration file
#   template:
     # src: my.cnf.j2
     # dest: /etc/my.cnf
#   notify:
#   - restart mysql

- name: open mysqld port
  firewalld:
    port: "{{ mysqld_port }}/tcp"
    zone: public
    permanent: true
    immediate: true
    state: enabled
  when: not (security_firewall is defined and not security_firewall)

- name: start and enable mysql service
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: create DB user
  mysql_user:
    name: "{{ mysql_username }}"
    password: "{{ mysql_password }}"
    priv: '*.*:ALL'
    host: '%'
    state: present

- name: configure SELinux to start mysql on any port
  seboolean:
    name: mysql_connect_any
    state: true
    persistent: yes
