---
# tasks file for web

- name: check if EPEL repo is already configured.
  stat:
    path: "{{ epel_repofile_path }}"
  register: epel_repofile

- name: install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: epel_repofile.stat.exists == False

- name: import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: epel_repofile.stat.exists == False

- name: install packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ base_packs }}"

- name: check if firewalld is running
  service:
    name: firewalld
    state: started
  check_mode: yes
  register: firewalld_service_status

- name: open httpd port
  firewalld:
    port: "{{ httpd_port }}/tcp"
    zone: public
    permanent: true
    immediate: true
    state: enabled
  when: firewalld_service_status.changed == false

- name: add site config
  template:
    src: templates/site.conf.j2
    dest: /etc/httpd/conf.d/site.conf
    mode: 0644

- name: ensure content directory exists
  file:
    path: "/var/www/{{ server_name }}"
    state: directory
    owner: apache
    group: apache
    mode: 0755

- name: copy content
  copy:
    src: "files/{{ item }}"
    dest: "/var/www/{{ server_name }}"
    owner: apache
    group: apache
    mode: 0644
  with_items:
    - epam_logo_2.jpg
    - index.html

- name: create php script
  template:
    src: templates/get.php.j2
    dest: "/var/www/{{ server_name }}/get.php"
    owner: apache
    group: apache
    mode: 0644

- name: start and enable httpd service
  systemd:
    name: httpd
    state: started
    enabled: yes

- name: allow httpd connect to remote database
  seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: yes