---
# tasks file for common

- name: install the latest version of zsh
  yum:
    name: "{{ item }}"
    state: latest
  register: installation
  with_items:
    - zsh
    - git

- name: get oh-my-zsh repo
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh'
    dest: '/root/.oh-my-zsh'
  when: installation|success
  register: get_repo

- name: check that .zshrc exists
  stat:
    path: '/root/.zshrc'
  register: zshrc

- name: create ~/.zshrc
  copy:
    src: '/root/.oh-my-zsh/templates/zshrc.zsh-template'
    dest: '/root/.zshrc'
    remote_src: true
  when: get_repo|success
        and zshrc.stat.exists

- name: change theme
  replace:
    path: '/root/.zshrc'
    regexp: '^ZSH_THEME="robbyrussell"$'
    replace: 'ZSH_THEME="amuse"'
    backup: yes

- name: change shell for root
  user:
    name: root
    shell: /bin/zsh