---
# defaults file for web

base_packs:
  - httpd
  - php
  - php-mysql
  - libsemanage-python
  - libselinux-python

httpd_port: '80'
server_name: 'ansible.test.epam.com'

epel_repo_url: "http://download.fedoraproject.org/pub/epel/{{ ansible_distribution_major_version }}/{{ ansible_userspace_architecture }}/e/epel-release-{{ ansible_distribution_major_version }}-{{ epel_release[ansible_distribution_major_version] }}.noarch.rpm"
epel_repo_gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repofile_path: '/etc/yum.repos.d/epel.repo'